### ISSUE TITLE
 killall: icinga2: no process killed

### ISSUE THREAD

**Issue by bodsch** [bodsch/ruby-icinga-cert-service#2]
```
cm-icinga2-master       | killall: icinga2: no process killed
cm-icinga2-master       | 2017-11-15 16:44:03 - TypeError - can't convert false into Integer:
cm-icinga2-master       |       /usr/local/lib/cert-service.rb:280:in `format'
cm-icinga2-master       |       /usr/local/lib/cert-service.rb:280:in `reload_icinga_config'
cm-icinga2-master       |       /usr/local/lib/cert-service/certificate_handler.rb:363:in `check_certificate'
cm-icinga2-master       |       /usr/local/bin/rest-service.rb:166:in `block (2 levels) in <class:CertServiceRest>'
```

**Comment by bodsch** [comment]
we use since version 0.14.4 the icinga2 API to restart the service
